webapp/post/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class AddPostForm(Form):
    post_title = StringField('Post Title', validators=[DataRequired()])
    post_description = StringField('Post Description', validators=[DataRequired()])

class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired()])

webapp/post/views.py
from flask import render_template, Blueprint, request, flash, redirect, url_for, Flask, jsonify, session
from webapp.models import Post
from .forms import AddPostForm, LoginForm

from webapp import db
import json

post_blueprint = Blueprint('post', __name__, template_folder='templates')


@post_blueprint.route('/', methods=['GET', 'POST'])
@post_blueprint.route('/home', methods=['GET', 'POST'])
def index():
    # form = LoginForm(request.form)
    all_post = Post.query.all()
    form = LoginForm(request.form)
    # return render_template('login.html', form=form)
    return render_template('posts.html', posts=all_post, form=form)

@post_blueprint.route('/login.json', methods=["POST"])
def login():
    # log the user in.
    email = request.form.get('email')
    password = request.form.get('password')

    session['email'] = email

    # jsonify = return a response object from flask that contains JSON instead of HTML
    # return jsonify({'cher': 'is awesome'})
    return jsonify({ 'username': email, 'password': password})

@post_blueprint.route('/aboutme.json', methods=["POST"])
def update_about_me():
    # save the new about me text in DB
    aboutme_text = request.form.get('about_me')
    print '\n\n\n\n', aboutme_text, '\n\n\n\n'
    return jsonify({'save': 'successful'})

@post_blueprint.route('/logout.json', methods=["POST"])
def logout():
    print "\n\n\n\nSession before we cleared it.\n", session
    session.clear()
    print "\n\n\n\nSession after we cleared it.\n", session
    return jsonify({'logout': 'successful'})

@post_blueprint.route('/add', methods=['GET', 'POST'])
def add_post():
    form = AddPostForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_post = Post(form.post_title.data, form.post_description.data)
            db.session.add(new_post)
            db.session.commit()
            flash('New post, {}, added!'.format(new_post.post_title), 'success')
            return redirect(url_for('post.index'))
        else:
            #flash_errors(form)
            flash('ERROR! Post was not added.', 'error')

    return render_template('add_post.html',
                           form=form)

# @post_blueprint.route('/login', methods=['GET', 'POST'])
# def login():
#     form = LoginForm(request.form)
#     if request.is_xhr:
#         if request.method == 'POST':
#             if form.validate_on_submit():
#                 email = request.get_json('email')
#                 password = request.get_json('password')
#                 user = User.query.filter_by(email).first()
#                 if user is not None and user.is_correct_password(password):
#                     user.authenticated = True
#                     db.session.add(user)
#                     db.session.commit()
#                     login_user(user)
#                     flash('Thanks for logging in, {}'.format(current_user.email))
#                     return redirect(url_for('post.index'))
#                 else:
#                     flash('ERROR! Incorrect login credentials.', 'error')
#     return render_template('login.html', form=form)
#
# @post_blueprint.route('/background_process', methods = ['GET', 'POST'])
# def background_process():
#     email = request.form['email']
#     password = request.form['password']
#     if email and password:
#         mail = jsonify({'email' : email})
#         pswd = jsonify({'password' : password})
#         user = User(mail = mail, pswd = pswd)
#         db.session.add(user)
#         db.session.commit()
#         login_user(user)
#         flash('Thanks for logging in, {}'.format(current_user.email))
#         return redirect(url_for('post.index'))
#     else:
#         flash('ERROR! Incorrect login credentials.', 'error')

webapp/users/views.py
from flask import render_template, Blueprint, request, flash, redirect, url_for, jsonify, abort, json, Flask, Response
from .forms import RegisterForm, LoginForm
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user

from webapp import db
from webapp.models import User

users_blueprint = Blueprint('users', __name__)

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering!', 'success')
                return redirect(url_for('post.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.is_xhr:
        if request.method == 'POST':
            if form.validate_on_submit():
                email = request.get_json('email')
                password = request.get_json('password')
                # email = request.json['email']
                # password = request.json['password']
                user = User.query.filter_by(email).first()
                if user is not None and user.is_correct_password(password):
                # if email is not None and password is not None:
                    user.authenticated = True
                    db.session.add(user)
                    db.session.commit()
                    login_user(user)
                    # value = [{ 'username': user.email, 'password': user.password_plaintext }]
                    # value = request.json[{ 'username': user.email, 'password': user.password_plaintext }]
                    # js = [ { "name" : filename, "size" : st.st_size , "url" : url_for('show', filename=filename)} ]
                    flash('Thanks for logging in, {}'.format(current_user.email))
                    return redirect(url_for('post.index'))
                    # return jsonify({ 'username': user.email, 'password': user.password_plaintext }), 201
                    # return jsonify(value)
                    # return Response(json.dumps(value),  mimetype='application/json')
                # mail = request.get_json('email')
                # pswd = request.get_json('password')
                # login = User(mail=request.form['email'], pswd=request.form['password'])
                # login = User(email=request.get_json('email'), password=request.get_json('password'))
                # user.authenticated = True
                # db.session.add(login)
                # db.session.commit()
                # flash('Thanks for logging in, {}'.format(current_user.email))
                # return redirect(url_for('post.index'))
                else:
                    flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)

        # form = LoginForm(request.form)
        # if request.is_xhr:
        #     if form.validate_on_submit():
        #         email = request.get_json('email')
        #         password = request.get_json('password')
        #         user = User.query.filter_by(email=email).first()
        #         if user is not None and user.is_correct_password(password):
        #             user.authenticated = True
        #             user = User.query.all()
        #             ujson = json.dumps(user)
        #             form = EventForm.from_json(ujson)
        #             # return jsonify({
        #             #     'count': len(user)
        #             # })
        #             return jsonify({'email' : email, 'password' : password})
        # # return jsonify({'email' : email, 'password' : password})
        # # return redirect(url_for('post.index'))
        # return Response(json.dumps(user),  mimetype='application/json')

@users_blueprint.route('/background_process', methods = ['GET', 'POST'])
def background_process():
    # email = request.form['email']
    # password = request.form['password']
    #
    # # if email and password:
    # # # if email is None or password is None:
    # #     return jsonify({'error' : 'Missing data!'})
    # # return jsonify({'email' : email, 'password' : password})
    # return jsonify({ 'email': email, 'password': password }), 201

    # data = get_data(email, password)  # Get your data
    # return json.dumps(data)
    # pass

    # email = request.get_json('email')
    # password = request.get_json('password')
    # if email is None or password is None:
    #     abort(400) # missing arguments
    # if User.query.filter_by(email = email).first() is not None:
    #     abort(400) # existing user
    # user = User(email = email, password = password)
    # db.session.add(user)
    # db.session.commit()
    # return json.dumps({ 'email': user.email, 'password': user.password }), 201

    email = request.form['email']
    password = request.form['password']
    if email and password:
        mail = jsonify({'email' : email})
        pswd = jsonify({'password' : password})
        user = User(mail = mail, pswd = pswd)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash('Thanks for logging in, {}'.format(current_user.email))
        return redirect(url_for('post.index'))
    else:
        flash('ERROR! Incorrect login credentials.', 'error')

# @users_blueprint.route('/api/users', methods = ['GET', 'POST'])
# def new_user():
#     email = request.get_json('email')
#     password = request.get_json('password')
#     if email is None or password is None:
#         abort(400) # missing arguments
#     if User.query.filter_by(email = email).first() is not None:
#         abort(400) # existing user
#     user = User(email = email, password = password)
#     db.session.add(user)
#     db.session.commit()
#     return jsonify({ 'email': user.email, 'password': user.password }), 201

@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))

webapp/templates/_form_macros.html
{% macro render_field(field) %}

<dt>{{ field.label }}:

<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>
 
{% endmacro %}

webapp/templates/add_post.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">

    <div class="page-header">
        <h2>Add a New Post</h2>
    </div>

    <form action="{{ url_for('post.add_post') }}" method="post">
        {{ form.csrf_token }}
        {{ form.post_title(placeholder="Post Title") }}
        {{ form.post_description(placeholder="Post Description") }}

        <button class="btn btn-sm btn-success" type="submit">Add Post</button>
    </form>

</div>

{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Flask React WebApp</title>
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">



    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('post.index') }}">Flask React WebApp</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('post.add_post') }}">Add</a></li>
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">

            {% if current_user.is_authenticated %}
                <li><a>Welcome</a></li>
            {% else %}
            {% from "_form_macros.html" import render_field %}
            <li class="dropdown" id="loginform">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
    			<ul id="login-dp" class="dropdown-menu">
    				<li>
    					 <div class="row">
    							<div class="col-md-12">
    								 <form class="form" role="form" method="post" accept-charset="UTF-8" id="login-nav">
                                             {{ form.csrf_token }}
                                             {{ render_field(form.email, placeholder="Email address") }}
                                             {{ render_field(form.password, placeholder="Password") }}
    										<div class="form-group">
    											 <button id="submit-btn" type="submit" class="btn btn-primary btn-block">Log in</button>
    										</div>
    								 </form>
    							</div>
    							<div class="bottom text-center">
    								New here ? <a href="{{ url_for('users.register') }}"><b>Join Us</b></a>
    							</div>
    					 </div>
    				</li>
    			</ul>
            </li>
            {% endif %}
            <span id="logout-section">
                {% if session.get('username') %}
                    <button id="logout">Logout</button>
                {% endif %}
            </span>

          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>

    <div id="alert-section">
        <!-- bootstrap alerts -->
    </div>

    <div class="container">
      <div class="content">

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
            <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
            <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
            <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}

        <!-- child template -->
        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>Flask React WebApp - 2016</p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="{{ url_for('static', filename='js/ajax-test.js') }}"></script>

  </body>
</html>

webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask React App</title>
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
    <h1>Welcome to Flask React App!</h1>
</body>
</html>

webapp/templates/login.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Log In</h2>
  </div>
    <form id="loginform" action="{{ url_for('users.login') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
    </dl>
    <button id="submit" class="btn btn-sm btn-success" type="submit" href="javascript:void();">Log In</button>
  </form>
  <br>
	<div id="successAlert" class="alert alert-success" role="alert" style="display:none;"></div>
	<div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;"></div>
  <em>Need an account? </em><a href="/register">Signup!!</a>
</div>

<script src="{{ url_for('static', filename='js/ajax-test.js') }}"></script>

{% endblock %}

webapp/templates/posts.html
{% extends "base.html" %}
{% block content %}

<h1>Welcome to the Flask React WebApp!</h1>

<div class="row">
  <div class="col-md-4">
    <table class="table table-striped" id="owned_stock_table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
            <td>{{ post.post_title }}</td>
            <td>{{ post.post_description }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

webapp/templates/register.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
<div class="user-registration">
  <div class="page-header">
    <h2>Please Register Your New Account</h2>
  </div>
<form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
      {{ render_field(form.confirm, placeholder="Confirm password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create New Account</button>
  </form>
</div>

{% endblock %}